[package]
name = "lisp-repl"
version = "0.1.0"
authors = ["jhiggins <johnmatthiggins@gmail.com>"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigdecimal = "0.3.0"
